### ISSUE TITLE
How to get started

### ISSUE THREAD

**Issue by cyrusinc** [dongri/oauthswift.herokuapp.com#6]
My Heroku experience is pretty limited and I couldn't gather too much from the readme. What steps should I take to get the redirct up and running w/Heroku?

**Comment by dongri** [comment]
@cyrussinc I setting deploy to heroku button on README.
https://github.com/dongri/oauthswift.herokuapp.com
<img width="491" alt="Screen Shot 2020-10-29 at 18 29 47" src="https://user-images.githubusercontent.com/878993/97550240-c0b9c400-1a14-11eb-9a43-a22114e3f4d7.png">

you can click button deploy to your heroku app. like https://oauthswift-sample.herokuapp.com

**Comment by cyrusinc** [comment]
Thanks so much for including the Heroku button! I have just used it to create the app on Heroku, but still somewhat uncertain on how I can modify the urls and get the redirect functionality working after this step

**Comment by cyrusinc** [comment]
Nevermind, looks like I've done it... Should have read the README more closely, I was not going to the proper URL
